title: From ubiquitous sensors to insights
description: Essay for my application to TUM's Master Program in Computer Science
google_analytics: 
show_downloads: true
theme: jekyll-theme-dinky

gems:
  - jekyll-mentions
