title: Are Data Structures and Algorithms obsolete today in the age of Machine Learning?
description: Essay for my application to TUM's Master Program in Data Engineering and Analytics
google_analytics: 
show_downloads: true
theme: jekyll-theme-dinky

gems:
  - jekyll-mentions
